/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_internacionalizacion;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JFrame;

/**
 *
 * @author evento
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        // Establecemos la localización por defecto
        Locale lc = new Locale("en","US");
        Locale.setDefault(lc);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHola = new javax.swing.JLabel();
        lbMundo = new javax.swing.JLabel();
        btnEspanol = new javax.swing.JButton();
        btnIngles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("e_internacionalizacion/Bundle"); // NOI18N
        setTitle(bundle.getString("MainFrame.title")); // NOI18N

        lbHola.setText(bundle.getString("MainFrame.lbHola.text")); // NOI18N

        lbMundo.setText(bundle.getString("MainFrame.lbMundo.text")); // NOI18N

        btnEspanol.setText(bundle.getString("MainFrame.btnEspanol.text")); // NOI18N
        btnEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspanolActionPerformed(evt);
            }
        });

        btnIngles.setText(bundle.getString("MainFrame.text")); // NOI18N
        btnIngles.setName(""); // NOI18N
        btnIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInglesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEspanol)
                    .addComponent(lbHola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMundo)
                    .addComponent(btnIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHola)
                    .addComponent(lbMundo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEspanol)
                    .addComponent(btnIngles))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspanolActionPerformed
        Locale lc = new Locale("es","VE");
        Locale.setDefault(lc);
        ResourceBundle rb;
        rb = ResourceBundle.getBundle("e_internacionalizacion/Bundle");
        
        // LLamar al método para cambiar el idioma usando el recurso
        cambiarIdioma(rb);
    }//GEN-LAST:event_btnEspanolActionPerformed

    private void btnInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInglesActionPerformed
        Locale lc = new Locale("en","US");
        Locale.setDefault(lc);
        ResourceBundle rb;
        rb = ResourceBundle.getBundle("e_internacionalizacion/Bundle_en_US");
        
        // LLamar al método para cambiar el idioma usando el recurso
        cambiarIdioma(rb);
    }//GEN-LAST:event_btnInglesActionPerformed

    private void cambiarIdioma(ResourceBundle resource) {
        // Cambiar el texto manualmente
        lbHola.setText(resource.getString("MainFrame.jLabel1.text"));
        lbMundo.setText(resource.getString("MainFrame.jLabel2.text"));
        btnEspanol.setText(resource.getString("MainFrame.jButton1.text"));
        btnIngles.setText(resource.getString("MainFrame.text"));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEspanol;
    private javax.swing.JButton btnIngles;
    private javax.swing.JLabel lbHola;
    private javax.swing.JLabel lbMundo;
    // End of variables declaration//GEN-END:variables
}
